### ISSUE TITLE
Post body empty when using "Authorization" header

### ISSUE THREAD

**Issue by timcreatewell** [typhoeus/typhoeus#261]
Hi there, I've posted something similar to this to the curb project as I'm receiving the same issue when I use curb... Thought someone here might have an idea though...

I'm trying to post a hash of data (post_data) as JSON to an external service (request_url).  The service requires authentication information (auth_date & auth_text) in the request header.

The code I'm trying to use to achieve this is as follows:

<pre>
response = Typhoeus::Request.post(
    request_url, 
    :body => post_data.to_json,
    :headers => { 
        "Auth-Date" => auth_date, 
        "Authorization" => auth_text,
        "Content-Type" => "application/json",
    },
    :proxy => "...snip..."  # (I'm pushing the request through fiddler so I can analyse the request/response)...
)
</pre>

If I run this code the response I get from the service is:  

<pre>
HTTP/1.1 411 Length Required
Content-Type: text/html
Date: Thu, 17 Jan 2013 05:51:00 GMT
Connection: close
Content-Length: 24

<h1>Length Required</h1>
</pre>

The request sent to the service is:  

<pre>
POST http://...snip... HTTP/1.1
Host: ...snip...
Accept: */*
Connection: Keep-Alive
Content-Type: application/json
Auth-Date: 2013-01-17T15:57:44+10:00
Authorization: ...snip...
</pre>

_... the body is missing!?_

_The strange thing is, if I remove the "Authorization" header, the body now appears in the request as well as the Content-Length header (but my request fails the service because it doesn't supply the correct authentication details)...!!_

Below is the request without the "Authorization" header:

<pre>
POST http://...snip... HTTP/1.1
Host: ...snip...
Connection: Keep-Alive
Accept: application/json
Content-Type: application/json
Auth-Date: 2013-01-17T15:48:53+10:00
Content-Length: 1055
Expect: 100-continue

{...snip...}
</pre>

Anyone have any ideas or am I missing something?

Thanks!
Tim.

**Comment by tinbka** [comment]
That trailing newline just made me waste 3 hours localizing the exact same problem! I was thinking it was related to SSL, encoding, or another gem. Ended up setting a server with SSL and reading raw posts.
Might it be worth to add a warning, at least when a :verbose flag enabled, when one of headers contains a newline?

**Comment by i0rek** [comment]
do they never contain newlines?

**Comment by tinbka** [comment]
Newline in the HTTP header marks its end. Although, by RFC the end of a header should be \r\n, web-servers should also recognize bare \n. E.g. https://stackoverflow.com/questions/5757290/http-header-line-break-style
Since curl joins each passed header with \r\n, \n in the header value turns into double newline. In its turn, double newline indicates the end of HTTP header block. E.g., https://stackoverflow.com/questions/6686261/what-at-the-bare-minimum-is-required-for-an-http-request
If such a header appears before Content-Length one, server may not read the request body at all.
Have a weird server behavior!

So, a header value passed to curl must not contain newlines unless you want to hack a request so that the header with a newline will explicitly be the last read in.
