### ISSUE TITLE
compatibility pledge

### ISSUE THREAD

**Issue by pravi** [typhoeus/typhoeus#470]
Currently debian has typhoeus 0.7.1 but diaspora insist it needs 0.7.2 because they won't support any version change, even bug fixes because it can break things.

Can you pledge to keep compatibility for minor versions? See https://wiki.debian.org/Teams/Ruby/UpstreamPledge

This will guarantee 0.7.x will not break ~> 0.7.1 lock. It would be even better if it was 0.8 won't break ~> 0.7 but that can be considered later, may be after 1.0

**Comment by i0rek** [comment]
@pravi thanks for asking. Typhoeus is using [semver](http://semver.org). That means the version is like that `MAJOR.MINOR.PATCH`. Although it says:

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

I consider Typhoeus to have a stable API and I am thinking about releasing 1.0.0. There is nothing that prevents that. I assume that with `minor` you mean `PATCH` in semver semantics. I can assure you that my goal is to not break in `PATCH` releases.

In the past I broke backwarts compatibility in a `MINOR` version, but only because this project has a long history of not releasing 1.0.0. I wouldn't do that anymore. The next breaking change will be released as `1.0.0`. Although I don't see that coming. There haven't been any breaking changes since the release of [`0.6.0`](https://github.com/typhoeus/typhoeus/blob/master/CHANGELOG.md#060) February 11, 2013 and the change was tiny:

> Request#url now also contains the url parameters.

Thanks again for asking.

**Comment by pravi** [comment]
Thanks! It would be good to add a note like this https://github.com/zombor/Validator/commit/b485289b45948ec3e829e8760b4221ee215931c9 in README.
