### ISSUE TITLE
Cookies are written to current directory instead of to Tempfile

### ISSUE THREAD

**Issue by samnissen** [typhoeus/typhoeus#590]
Typhoeus cookie stores are filling my current directory, and are not garbage collected, despite being initialized as Tempfiles:

```ruby
require 'typhoeus'
@cookie_file = Tempfile.new('cookies') 
# => #<Tempfile:/var/folders/cd/ty85n3x95_z656kbwjfrx1w1jqbs0p/T/cookies20180215-12348-id2v8w>
request_options = { timeout: 10000,
  followlocation: true,
  cookiefile: @cookie_file,
  cookiejar: @cookie_file }
q = "http://mcelroyshows.com"
request = Typhoeus::Request.new(q, request_options)
`ls`.split("\n").map{|f| f =~ /\A\#\<File:0x0.*\>\z/ }.any?
# => false
request.run
`ls`.split("\n").map{|f| f =~ /\A\#\<File:0x0.*\>\z/ }.any?
# => true
File.read("#<File:0x007fb26aa9f5c8>")
# => "# Netscape HTTP Cookie File\n# https://curl.haxx.se/docs/http-cookies.html\n# This file was generated by libcurl! Edit at your own risk.\n\nmcelroyshows.com\tFALSE\t/\tFALSE\t0\tcrumb\tBeSzFHXiSveNYzE0MzUxY2RiYjc4NjUzM2JhODAwMTQ4YmFjODM0\n"
File.read @cookie_file.path
# => ""
```

- typhoeus v 1.3.0
- ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin17]
- macOS 10.13.2

**Comment by PericlesTheo** [comment]
The issue is that `cookiefile` and `cookiejar` are expected to be paths instead.

If you change your `request_options` to request_options = { timeout: 10000, cookiefile: @cookie_file.path, cookiejar: @cookie_file.path }` it should work just fine.

What ends up happening under the hood is the `cookiejar` is expected to be a string ([ethon option definition](https://github.com/typhoeus/ethon/blob/master/lib/ethon/curls/options.rb#L342)) so it will try to [coerce](https://github.com/typhoeus/ethon/blob/master/lib/ethon/curls/options.rb#L58) it. In the example above `#<File:0x007fb26aa9f5c8>` is the representation of `@cookie_file.to_s`

**Comment by samnissen** [comment]
Yes, I completely missed this requirement. Thank you!
