### ISSUE TITLE
No new tags since May 2020

### ISSUE THREAD

**Issue by dprater** [typhoeus/typhoeus#719]
I see there have been quite a few commits to this repo since May of 2020, but no tags created, and rubygems still has version 1.4.0 from May 2020. Any reason not to create a new tag and send it up to RubyGems?

**Comment by isikyus** [comment]
While there have been commits since 2020, they haven't been from people who own the gem on Rubygems. Checking https://rubygems.org/gems/typhoeus and cross-referencing with Git history, I can see three owners: `@hanshasselberg`, `@dbalatero`, and `@pauldix`. Of those three only `hanshasselberg` has been active since 2011 in this repository, and [that was in 2020](https://github.com/typhoeus/typhoeus/commits?author=hanshasselberg).

I imagine there will be no further releases unless one of those three people returns to working on Typhoeus, or adds another gem owner on Rubygems.

**Comment by hanshasselberg** [comment]
Hi @dprater and @isikyus! Even though I am not developing I am trying to keep an eye on the repositiories and am happy to cut a release if needed. Also if someone is interesting in doing some work on ethon or typhoeus, I am more than happy to chat about it.

**Comment by dprater** [comment]
@hanshasselberg - if the gem is, in fact, being maintained (either by you or by the community), it would be nice to make those changes/updates available for those using it. Also, when we run security analysis tools on our app, which utilizes Typhoeus, we get dinged because the gem appears to be unmaintained, given that the last tags is from 3 years ago. I don't now how difficult it is to send a release to RubyGems, but it would be great if you could. If there is no plan to continue updating the Gem, might be worthwhile to note that in the README so folks know what to expect.

**Comment by hanshasselberg** [comment]
https://rubygems.org/gems/typhoeus v1.4.1 released.

**Comment by dprater** [comment]
Thanks so much!
